### ISSUE TITLE
Solution proposal

### ISSUE THREAD

**Issue by road2015** [JRRN/MongoUniversity#2]
db.grades.aggregate([
    { $match: { scores: { $elemMatch: { type: { $ne: "quiz" } } }  } },
    { $project: { class_id: 1, scores: 1 } },
    { $unwind: "$scores" },
    { $group:{ 
        _id : "$class_id",
        avg: { "$avg" : "$scores.score" }
    } },
    { $sort: { avg: -1 } }
]).pretty()

//outputs

{ "_id" : 1, "avg" : 58.3972086085214 }
{ "_id" : 26, "avg" : 58.146256097154044 }
{ "_id" : 9, "avg" : 55.959975227145435 }
{ "_id" : 11, "avg" : 55.02367012378276 }
{ "_id" : 16, "avg" : 54.63564222916665 }
{ "_id" : 5, "avg" : 54.164419161512036 }
{ "_id" : 4, "avg" : 53.10783283118923 }
{ "_id" : 10, "avg" : 53.0566202035236 }
{ "_id" : 20, "avg" : 52.64039494378339 }
{ "_id" : 13, "avg" : 51.76529805087405 }
{ "_id" : 7, "avg" : 50.81480967725755 }
{ "_id" : 29, "avg" : 50.23323724268069 }
{ "_id" : 14, "avg" : 50.170689358225644 }
{ "_id" : 23, "avg" : 50.1215954808574 }
{ "_id" : 19, "avg" : 50.004525261539605 }
{ "_id" : 24, "avg" : 49.72083585510093 }
{ "_id" : 0, "avg" : 49.55606780344129 }
{ "_id" : 21, "avg" : 48.92872432873295 }
{ "_id" : 3, "avg" : 48.87418039035176 }
{ "_id" : 27, "avg" : 47.61594896756117 }

**Comment by JRRN** [comment]
Pull Request @road2015
